name: Publish new package with the latest PSL

on:
  push:
    tags:
    - "v*.0" # kickstart manual release cycle
  #schedule:
  #  - cron: "35 1 * * *"

jobs:
  publish-package-with-psl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine requests

    - name: Check if merged
      run: |
        git checkout publish
        git branch --merged main || git merge main

    - name: Check if PSL has been changed
      run: |
        pip install .
        python -m publicsuffixlist.update

    - name: Commit the change
      run: |
        git config user.name "ko-zu (github-actions)"
        git config user.email "causeless@gmail.com"
        
        # replace the version
        VERSION=$(sed -e 's/^__version__ = "([0-9\.]\+)"$/\1/' setup.py)
        NEWVERSION=$(date -u "+%Y%m%d%H%M%S")
        sed -i 's/^\(__version__ = "[0-9\.]\+\).[0-9]\+"$/\1.'${NEWVERSION}'"/' setup.py
        NEWTAG=$(sed -e 's/^__version__ = "([0-9\.]\+)"$/v\1/' setup.py)

        # break if there is no change in the list, or not a manual release request
        echo ${VERSION} | grep -qE "\.0$" || \
          ! git diff --exit-code --quiet publicsuffixlist/public_suffix_list.dat || \
          exit 1

        pip install .
        python setup.py sdist --formats=gztar
        python setup.py bdist_wheel --universal
        python -m publicsuffixlist.test || echo "Some tests failed." && exit 1
        
        git add setup.py publicsuffixlist/public_suffix_list.dat
        git commit -m "automated release"
        git push origin publish
        git tag ${NEWTAG}
        git push origin ${NEWTAG}
    
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

